import torch
import torch.nn as nn
import torch.nn.functional as F

try:
    from timm.models.layers import to_2tuple, trunc_normal_
except ImportError:
    # Fallback if timm is not available
    def to_2tuple(x):
        if isinstance(x, (list, tuple)):
            return x
        return (x, x)
    
    def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
        """Fills the input Tensor with values drawn from a truncated normal distribution."""
        def norm_cdf(x):
            # Computes standard normal cumulative distribution function
            return (1. + torch.erf(x / torch.sqrt(torch.tensor(2.)))) / 2.
        
        if (mean < a - 2 * std) or (mean > b + 2 * std):
            raise ValueError("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                             "The distribution of values may be incorrect.")
        
        with torch.no_grad():
            # Values are generated by using a truncated uniform distribution and
            # then using the inverse CDF for the normal distribution.
            # Get upper and lower cdf values
            l = norm_cdf((a - mean) / std)
            u = norm_cdf((b - mean) / std)
            
            # Uniformly fill tensor with values from [l, u], then translate to
            # [2l-1, 2u-1].
            tensor.uniform_(2 * l - 1, 2 * u - 1)
            
            # Use inverse cdf for normal distribution to get truncated
            # standard normal
            tensor.erfinv_()
            
            # Transform to proper mean, std
            tensor.mul_(std * torch.sqrt(torch.tensor(2.)))
            tensor.add_(mean)
            
            # Clamp to ensure it's in the proper range
            tensor.clamp_(min=a, max=b)
            return tensor


def default_conv(in_channels, out_channels, kernel_size, bias=True):
    return nn.Conv2d(
        in_channels, out_channels, kernel_size,
        padding=(kernel_size // 2), bias=bias)


def _compute_num_heads(n_feats):
    """
    Compute number of attention heads ensuring n_feats is divisible by num_heads.
    Default: aim for head_dim around 10 (nf=50 -> 5 heads, nf=64 -> 6 or 8 heads)
    """
    # Find the largest divisor of n_feats that gives reasonable head_dim
    for num_heads in [10, 8, 5, 6, 4, 3, 2, 1]:
        if n_feats % num_heads == 0:
            head_dim = n_feats // num_heads
            if 4 <= head_dim <= 64:  # Reasonable head dimension range
                return num_heads
    # Fallback: return 1 (always valid)
    return 1


class SwinT(nn.Module):
    """
    Swin Transformer Layer adapted for Super-Resolution.
    
    As per DHTCUN paper Section III.C:
    "Unlike the original STL which uses the components twice,
     we have used the components inside STL just once"
    So depth=1.
    """
    def __init__(self, n_feats=50):
        super(SwinT, self).__init__()
        
        # DHTCUN uses depth=1 (unlike original Swin with depth=2)
        depth = 1
        
        # Compute num_heads dynamically to ensure divisibility
        num_heads = _compute_num_heads(n_feats)
        
        # Adaptive window size: use 8 as default (works for most feature map sizes)
        window_size = 8
        
        # Resolution is adaptive - we pass None and compute dynamically
        mlp_ratio = 2.0
        
        m = []
        m.append(BasicLayer(
            dim=n_feats,
            depth=depth,
            num_heads=num_heads,
            window_size=window_size,
            mlp_ratio=mlp_ratio,
            qkv_bias=True,
            qk_scale=None,
            norm_layer=nn.LayerNorm))
        self.transformer_body = nn.Sequential(*m)

    def forward(self, x):
        res = self.transformer_body(x)
        return res


class BasicLayer(nn.Module):
    """
    A single Swin Transformer layer.
    """
    def __init__(self, dim, embed_dim=50, depth=2, num_heads=8, window_size=8,
                 mlp_ratio=1., qkv_bias=True, qk_scale=None, norm_layer=None):
        super().__init__()
        self.dim = dim
        self.depth = depth
        self.window_size = window_size
        
        # Build Swin Transformer blocks
        self.blocks = nn.ModuleList([
            SwinTransformerBlock(
                dim=dim,
                num_heads=num_heads,
                window_size=window_size,
                shift_size=0 if (i % 2 == 0) else window_size // 2,
                mlp_ratio=mlp_ratio,
                qkv_bias=qkv_bias,
                qk_scale=qk_scale,
                norm_layer=norm_layer)
            for i in range(depth)])
        
        self.patch_embed = PatchEmbed(embed_dim=dim, norm_layer=norm_layer)
        self.patch_unembed = PatchUnEmbed(embed_dim=dim)

    def check_image_size(self, x):
        """Pad image if needed to be divisible by window_size."""
        _, _, h, w = x.size()
        mod_pad_h = (self.window_size - h % self.window_size) % self.window_size
        mod_pad_w = (self.window_size - w % self.window_size) % self.window_size
        if mod_pad_h != 0 or mod_pad_w != 0:
            x = F.pad(x, (0, mod_pad_w, 0, mod_pad_h), 'reflect')
        return x, h, w

    def forward(self, x):
        x, h, w = self.check_image_size(x)
        _, _, H, W = x.size()
        x_size = (H, W)
        
        x = self.patch_embed(x)
        for blk in self.blocks:
            x = blk(x, x_size)
        x = self.patch_unembed(x, x_size)
        
        # Crop back to original size
        if h != H or w != W:
            x = x[:, :, 0:h, 0:w].contiguous()
        return x


class SwinTransformerBlock(nn.Module):
    """
    Swin Transformer Block with window-based multi-head self-attention.
    """
    def __init__(self, dim, num_heads, window_size=8, shift_size=0,
                 mlp_ratio=4., qkv_bias=True, qk_scale=None, 
                 act_layer=nn.GELU, norm_layer=nn.LayerNorm):
        super().__init__()
        self.dim = dim
        self.num_heads = num_heads
        self.window_size = window_size
        self.shift_size = shift_size
        self.mlp_ratio = mlp_ratio
        
        assert 0 <= self.shift_size < self.window_size, \
            "shift_size must be in 0-window_size"

        self.norm1 = norm_layer(dim)
        self.attn = WindowAttention(
            dim, window_size=to_2tuple(self.window_size), num_heads=num_heads,
            qkv_bias=qkv_bias, qk_scale=qk_scale)

        self.norm2 = norm_layer(dim)
        mlp_hidden_dim = int(dim * mlp_ratio)
        self.mlp = Mlp(in_features=dim, hidden_features=mlp_hidden_dim, 
                       act_layer=act_layer)

        # Attention mask for shifted window attention
        if self.shift_size > 0:
            attn_mask = self.calculate_mask((window_size, window_size))
        else:
            attn_mask = None
        self.register_buffer("attn_mask", attn_mask)

    def calculate_mask(self, x_size):
        """Calculate attention mask for SW-MSA."""
        H, W = x_size
        if H % self.window_size == 0 and W % self.window_size == 0:
            return None
        
        img_mask = torch.zeros((1, H, W, 1))
        h_slices = (slice(0, -self.window_size),
                    slice(-self.window_size, -self.shift_size),
                    slice(-self.shift_size, None))
        w_slices = (slice(0, -self.window_size),
                    slice(-self.window_size, -self.shift_size),
                    slice(-self.shift_size, None))
        cnt = 0
        for h in h_slices:
            for w in w_slices:
                img_mask[:, h, w, :] = cnt
                cnt += 1

        mask_windows = window_partition(img_mask, self.window_size)
        mask_windows = mask_windows.view(-1, self.window_size * self.window_size)
        attn_mask = mask_windows.unsqueeze(1) - mask_windows.unsqueeze(2)
        attn_mask = attn_mask.masked_fill(attn_mask != 0, float(-100.0)).masked_fill(
            attn_mask == 0, float(0.0))
        return attn_mask

    def forward(self, x, x_size):
        H, W = x_size
        B, L, C = x.shape
        shortcut = x
        
        x = self.norm1(x)
        x = x.view(B, H, W, C)

        # Cyclic shift
        if self.shift_size > 0:
            shifted_x = torch.roll(x, shifts=(-self.shift_size, -self.shift_size), 
                                   dims=(1, 2))
        else:
            shifted_x = x

        # Partition into windows
        x_windows = window_partition(shifted_x, self.window_size)
        x_windows = x_windows.view(-1, self.window_size * self.window_size, C)

        # W-MSA/SW-MSA
        if self.shift_size > 0 or x_size[0] % self.window_size != 0 or x_size[1] % self.window_size != 0:
            attn_mask = self.calculate_mask(x_size)
            if attn_mask is not None:
                attn_mask = attn_mask.to(x.device)
        else:
            attn_mask = None
            
        attn_windows = self.attn(x_windows, mask=attn_mask)

        # Merge windows
        attn_windows = attn_windows.view(-1, self.window_size, self.window_size, C)
        shifted_x = window_reverse(attn_windows, self.window_size, H, W)

        # Reverse cyclic shift
        if self.shift_size > 0:
            x = torch.roll(shifted_x, shifts=(self.shift_size, self.shift_size), 
                           dims=(1, 2))
        else:
            x = shifted_x
        x = x.view(B, H * W, C)

        # FFN
        x = shortcut + x
        x = x + self.mlp(self.norm2(x))
        return x


class WindowAttention(nn.Module):
    """
    Window-based multi-head self-attention with relative position bias.
    """
    def __init__(self, dim, window_size, num_heads, qkv_bias=True, qk_scale=None):
        super().__init__()
        self.dim = dim
        self.window_size = window_size
        self.num_heads = num_heads
        head_dim = dim // num_heads
        self.scale = qk_scale or head_dim ** -0.5

        # Relative position bias table
        self.relative_position_bias_table = nn.Parameter(
            torch.zeros((2 * window_size[0] - 1) * (2 * window_size[1] - 1), num_heads))

        # Get pair-wise relative position index
        coords_h = torch.arange(self.window_size[0])
        coords_w = torch.arange(self.window_size[1])
        coords = torch.stack(torch.meshgrid([coords_h, coords_w], indexing='ij'))
        coords_flatten = torch.flatten(coords, 1)
        relative_coords = coords_flatten[:, :, None] - coords_flatten[:, None, :]
        relative_coords = relative_coords.permute(1, 2, 0).contiguous()
        relative_coords[:, :, 0] += self.window_size[0] - 1
        relative_coords[:, :, 1] += self.window_size[1] - 1
        relative_coords[:, :, 0] *= 2 * self.window_size[1] - 1
        relative_position_index = relative_coords.sum(-1)
        self.register_buffer("relative_position_index", relative_position_index)

        self.qkv = nn.Linear(dim, dim * 3, bias=qkv_bias)
        self.proj = nn.Linear(dim, dim)

        trunc_normal_(self.relative_position_bias_table, std=.02)
        self.softmax = nn.Softmax(dim=-1)

    def forward(self, x, mask=None):
        B_, N, C = x.shape
        qkv = self.qkv(x).reshape(B_, N, 3, self.num_heads, C // self.num_heads).permute(2, 0, 3, 1, 4)
        q, k, v = qkv[0], qkv[1], qkv[2]

        q = q * self.scale
        attn = (q @ k.transpose(-2, -1))

        # Add relative position bias
        relative_position_bias = self.relative_position_bias_table[
            self.relative_position_index.view(-1)].view(
                self.window_size[0] * self.window_size[1],
                self.window_size[0] * self.window_size[1], -1)
        relative_position_bias = relative_position_bias.permute(2, 0, 1).contiguous()
        attn = attn + relative_position_bias.unsqueeze(0)

        if mask is not None:
            nW = mask.shape[0]
            attn = attn.view(B_ // nW, nW, self.num_heads, N, N) + \
                   mask.unsqueeze(1).unsqueeze(0)
            attn = attn.view(-1, self.num_heads, N, N)
            
        attn = self.softmax(attn)
        x = (attn @ v).transpose(1, 2).reshape(B_, N, C)
        x = self.proj(x)
        return x


def window_partition(x, window_size):
    """
    Args:
        x: (B, H, W, C)
        window_size (int): window size
    Returns:
        windows: (num_windows*B, window_size, window_size, C)
    """
    B, H, W, C = x.shape
    x = x.view(B, H // window_size, window_size, W // window_size, window_size, C)
    windows = x.permute(0, 1, 3, 2, 4, 5).contiguous().view(-1, window_size, window_size, C)
    return windows


def window_reverse(windows, window_size, H, W):
    """
    Args:
        windows: (num_windows*B, window_size, window_size, C)
        window_size (int): Window size
        H (int): Height of image
        W (int): Width of image
    Returns:
        x: (B, H, W, C)
    """
    B = int(windows.shape[0] / (H * W / window_size / window_size))
    x = windows.view(B, H // window_size, W // window_size, window_size, window_size, -1)
    x = x.permute(0, 1, 3, 2, 4, 5).contiguous().view(B, H, W, -1)
    return x


class Mlp(nn.Module):
    def __init__(self, in_features, hidden_features=None, out_features=None, 
                 act_layer=nn.GELU):
        super().__init__()
        out_features = out_features or in_features
        hidden_features = hidden_features or in_features
        self.fc1 = nn.Linear(in_features, hidden_features)
        self.act = act_layer()
        self.fc2 = nn.Linear(hidden_features, out_features)

    def forward(self, x):
        x = self.fc1(x)
        x = self.act(x)
        x = self.fc2(x)
        return x


class PatchEmbed(nn.Module):
    """
    Image to Patch Embedding for Swin Transformer.
    """
    def __init__(self, embed_dim=50, norm_layer=None):
        super().__init__()
        self.embed_dim = embed_dim
        if norm_layer is not None:
            self.norm = norm_layer(embed_dim)
        else:
            self.norm = None

    def forward(self, x):
        # x: (B, C, H, W) -> (B, H*W, C)
        x = x.flatten(2).transpose(1, 2)
        if self.norm is not None:
            x = self.norm(x)
        return x


class PatchUnEmbed(nn.Module):
    """
    Patch Embedding to Image for Swin Transformer.
    """
    def __init__(self, embed_dim=50):
        super().__init__()
        self.embed_dim = embed_dim

    def forward(self, x, x_size):
        B, HW, C = x.shape
        x = x.transpose(1, 2).view(B, self.embed_dim, x_size[0], x_size[1])
        return x


if __name__ == '__main__':
    # Test with different feature dimensions
    for nf in [50, 64, 93, 128]:
        x = torch.randn((1, nf, 48, 48))
        model = SwinT(n_feats=nf)
        out = model(x)
        print(f"SwinT test: nf={nf}, input={x.shape}, output={out.shape}")